name: Code Quality - Static Code - Cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cppcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt -y install cppcheck
    - name: Run cppcheck
      run: cppcheck --enable=all -i Alzheimers_soul_sathi_src.c src/test_project.h -i Alzheimers_soul_sathi_src.c test -i Alzheimers_soul_sathi_src.c unity Alzheimers_soul_sathi_src.c
