name: C/C++ -Build Status

on: 
  push:
     branches: [main]
  pull_request:
     branches: [main]

jobs:
  build:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: master
      run: make -C Alzheimers_soul_sathi_src.c

   
